# Generated by Django 3.0.2 on 2020-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('state', models.CharField(blank=True, choices=[('todo', 'Todo'), ('in-progress', 'In Progress'), ('done', 'Done')], max_length=12)),
            ],
        ),
    ]
