# Generated by Django 3.0.2 on 2020-01-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200115_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
