# Generated by Django 3.0.2 on 2020-01-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
