# Generated by Django 3.0.2 on 2020-01-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200115_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
    ]
